// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameContainer = "containers"

// Container mapped from table <containers>
type Container struct {
	ID     int64  `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	Name   string `gorm:"column:name;type:character varying(255);not null" json:"name"`
	NodeID int64  `gorm:"column:node_id;type:bigint;not null" json:"node_id"`
}

// TableName Container's table name
func (*Container) TableName() string {
	return TableNameContainer
}
