// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNamespace = "namespace"

// Namespace mapped from table <namespace>
type Namespace struct {
	Name        string    `gorm:"column:name;type:varchar(100);primaryKey" json:"name"`
	Status      string    `gorm:"column:status;type:enum('Active','Terminating');not null" json:"status"`
	UpdatedTime time.Time `gorm:"column:updated_time;type:datetime;default:CURRENT_TIMESTAMP" json:"updated_time"`
	CreatedTime time.Time `gorm:"column:created_time;type:datetime;default:CURRENT_TIMESTAMP" json:"created_time"`
}

// TableName Namespace's table name
func (*Namespace) TableName() string {
	return TableNameNamespace
}
