version: '3'

services:
  etcd:
    image: bitnami/etcd:latest
    environment:
      - ETCD_NAME=etcd
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_INITIAL_CLUSTER=etcd=http://etcd:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=k2edge
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCDCTL_API=3
    ports:
      - "2379:2379"
      - "2380:2380"