// Code generated by goctl. DO NOT EDIT.
package types

type CordonRequest struct {
	Selector Metadata `json:"selector"`
}

type CordonResponse struct {
	Error Error `json:"error,omitempty"`
}

type UncordonRequest struct {
	Selector Metadata `json:"selector"`
}

type UncordonResponse struct {
	Error Error `json:"error,omitempty"`
}

type DrainRequest struct {
	Selector Metadata `json:"selector"`
}

type DrainResponse struct {
	Error Error `json:"error,omitempty"`
}

type Metadata struct {
	Namespace string `json:"namespace"`
	Kind      string `json:"kind"`
	Name      string `json:"name"`
}

type Error struct {
	Todo string `json:"todo"`
}

type ContainerConfig struct {
	Todo string `json:"todo"`
}

type ContainerStatus struct {
	Todo string `json:"todo"`
}

type Container struct {
	Metadata Metadata        `json:"metadata"`
	Config   ContainerConfig `json:"config"`
	Status   ContainerStatus `json:"status"`
}

type CronJobConfig struct {
	Todo string `json:"todo"`
}

type CronJobStatus struct {
	Todo string `json:"todo"`
}

type CronJob struct {
	Metadata Metadata      `json:"metadata"`
	Config   CronJobConfig `json:"config"`
	Status   CronJobStatus `json:"status"`
}

type Command struct {
	Todo string `json:"todo"`
}

type Namespace struct {
	Name string `json:"name"`
}

type CreateCronJobRequest struct {
	Todo string `json:"todo"`
}

type CreateCronJobResponse struct {
	Error Error `json:"error,omitempty"`
}

type GetCronJobRequest struct {
	Todo string `json:"todo"`
}

type GetCronJobResponse struct {
	CronJob CronJob `json:"cronjob"`
}

type DeleteCronJobRequest struct {
	Todo string `json:"todo"`
}

type DeleteCronJobResponse struct {
	Error Error `json:"error,omitempty"`
}

type ApplyCronJobRequest struct {
	Todo string `json:"todo"`
}

type ApplyCronJobResponse struct {
	Error Error `json:"error,omitempty"`
}

type CreateNamespaceRequest struct {
	Todo string `json:"todo"`
}

type CreateNamespaceResponse struct {
	Error Error `json:"error,omitempty"`
}

type GetNamespaceRequest struct {
	Todo string `json:"todo"`
}

type GetNamespaceResponse struct {
	Namespace Namespace `json:"namespace"`
}

type ListNamespacesRequest struct {
	Todo string `json:"todo"`
}

type ListNamespacesResponse struct {
	Namespaces []Namespace `json:"namespaces"`
}

type DeleteNamespaceRequest struct {
	Todo string `json:"todo"`
}

type DeleteNamespaceResponse struct {
	Error Error `json:"error,omitempty"`
}

type ClusterInfoResponse struct {
	Todo string `json:"todo"`
}
