/*
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CreateNamespaceRequest struct {
	Name string `json:"name"`
	Labels string `json:"labels"`
	Annotations string `json:"annotations,omitempty"`
}
