/*
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NamespaceSimpleInfo struct {
	Name string `json:"name"`
	Status string `json:"status"`
	Time string `json:"time"`
}
