/*
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Namespace struct {
	Name string `json:"name"`
	Labels string `json:"labels"`
	Annotations string `json:"annotations"`
	Status string `json:"status"`
	CreateTime string `json:"create_time"`
}
