// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"k2edge/worker/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/version",
				Handler: VersionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/run",
				Handler: RunContainerHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/stop",
				Handler: StopContainerHandler(serverCtx),
			},
		},
	)
}
