/*
 * worker api
 *
 * worker api
 *
 * API version: 
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CronJob struct {
	Metadata *Metadata `json:"metadata"`
	Config *CronJobConfig `json:"config"`
	Status *CronJobStatus `json:"status"`
}
