/*
 * worker api
 *
 * worker api
 *
 * API version: 
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CronJobConfig struct {
	Todo string `json:"todo"`
}
