/*
 * worker api
 *
 * worker api
 *
 * API version: 
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Container struct {
	Metadata *Metadata `json:"metadata"`
	Config *ContainerConfig `json:"config"`
	Status *ContainerStatus `json:"status"`
}
