/*
 * worker api
 *
 * worker api
 *
 * API version: 
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Metadata struct {
	Namespace string `json:"namespace"`
	Kind string `json:"kind"`
	Name string `json:"name"`
}
