/*
 * worker api
 *
 * worker api
 *
 * API version: 
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ListContainersRequest struct {
	Size bool `json:"size,omitempty"`
	All bool `json:"all,omitempty"`
	Latest bool `json:"latest,omitempty"`
	Since string `json:"since,omitempty"`
	Before string `json:"before,omitempty"`
	Limit int32 `json:"limit,omitempty"`
}
