/*
 * worker api
 *
 * worker api
 *
 * API version: 
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ExecRequest struct {
	Selector *Metadata `json:"selector"`
	Command *Command `json:"command"`
}
