// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"k2edge/master/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: CreateCronJobHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/get",
				Handler: GetCronJobHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: DeleteCronJobHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/apply",
				Handler: ApplyCronJobHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/rollout/history",
				Handler: HistoryCronJobHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/rollout/undo",
				Handler: UndoCronJobHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/logs",
				Handler: LogsCronJobHandler(serverCtx),
			},
		},
		rest.WithPrefix("/cronjob"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: CreateNamespaceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/get",
				Handler: GetNamespaceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: ListNamespacesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: DeleteNamespaceHandler(serverCtx),
			},
		},
		rest.WithPrefix("/namespace"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: ClusterInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/cluster"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/top",
				Handler: NodeTopHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cordon",
				Handler: CordonHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/uncordon",
				Handler: UncordonHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/drain",
				Handler: DrainHandler(serverCtx),
			},
		},
		rest.WithPrefix("/node"),
	)
}
