// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"k2edge/master/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: CreateCronJobHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/get",
				Handler: GetCronJobHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: DeleteCronJobHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/apply",
				Handler: ApplyCronJobHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/rollout/history",
				Handler: HistoryCronJobHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/rollout/undo",
				Handler: UndoCronJobHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/logs",
				Handler: LogsCronJobHandler(serverCtx),
			},
		},
		rest.WithPrefix("/cronjob"),
	)
}
